version: "3.8"
services:
  docker101:
    container_name: docker101
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8080:${HTTP_PORT}
      - 5858:5858
    volumes:
      - ./src:/var/www/webapp/src:cached
      - ./templates:/var/www/webapp/templates:cached
