version: "3.8"
services:
  docker101:
    container_name: docker101
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 8080:${HTTP_PORT}
    volumes:
      - ./app:/var/www/webapp/app:cached
      - /var/www/node_modules
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis_db
    ports:
      - 6379:6379
